from spider_man.crawler.extractors import JsonExtractor
from spider_man.crawler.fields import JsonField
from spider_man.spiders.jumei.good.items.good_dynamic_detail_item import GoodDynamicDetailItem

__all__ = ['GoodDynamicDetailPageExtractor']


class GoodDynamicDetailPageExtractor():
    @classmethod
    def get_item(cls, response):
        return cls._extract(response)

    @classmethod
    def _extract(cls, response):
        item = GoodDynamicDetailExtractor.get_item(response)
        good_item = GoodDynamicDetailItem()
        good_item['item_id'] = item.item_id
        good_item['type'] = item.type
        good_item['status'] = item.status
        good_item['is_sellable'] = item.is_sellable
        good_item['selling_forms'] = item.selling_forms
        good_item['discount'] = item.discount
        good_item['market_price'] = item.market_price
        good_item['size'] = item.size
        good_item['default_sku'] = item.default_sku
        good_item['tag_ids'] = item.tag_ids
        good_item['show_category'] = item.show_category
        good_item['warehouse_code'] = item.warehouse_code
        good_item['sale_type'] = item.sale_type
        good_item['sale_type_id'] = item.sale_type_id
        good_item['merchant_id'] = item.merchant_id
        good_item['product_id'] = item.product_id
        good_item['brand_id'] = item.brand_id
        good_item['category_v3_3'] = item.category_v3_3
        good_item['category_v3_4'] = item.category_v3_4
        good_item['category'] = item.category
        good_item['shipping_system_id'] = item.shipping_system_id
        good_item['product_attr_aca'] = item.product_attr_aca
        good_item['refund_policy'] = item.refund_policy
        good_item['exchange_policy'] = item.exchange_policy
        good_item['value_of_goods'] = item.value_of_goods
        good_item['tax'] = item.tax
        good_item['anchor_uid'] = item.anchor_uid
        good_item['is_support_refund_window'] = item.is_support_refund_window
        good_item['countries'] = item.countries
        good_item['author_id'] = item.author_id
        good_item['video_id'] = item.video_id
        good_item['is_hide_juhe_sku'] = item.is_hide_juhe_sku
        good_item['size_attr'] = item.size_attr
        good_item['fare'] = item.fare
        good_item['baoyou'] = item.baoyou
        good_item['area_code'] = item.area_code
        good_item['area_name'] = item.area_name
        good_item['shipping_system_type'] = item.shipping_system_type
        good_item['shipping_time'] = item.shipping_time
        good_item['baoyou_desc'] = item.baoyou_desc
        good_item['baoyou_text'] = item.baoyou_text
        good_item['wuliu_text'] = item.wuliu_text
        good_item['guonei_baoyou'] = item.guonei_baoyou
        good_item['bonded_area_id'] = item.bonded_area_id
        good_item['jumei_price'] = item.jumei_price
        good_item['start_time'] = item.start_time
        good_item['end_time'] = item.end_time
        good_item['second_kill_time'] = item.second_kill_time
        good_item['buyer_number'] = item.buyer_number
        good_item['wish_number'] = item.wish_number
        good_item['status_num'] = item.status_num
        good_item['sale_short_name'] = item.sale_short_name
        good_item['sku_min_price'] = item.sku_min_price
        good_item['sku_max_price'] = item.sku_max_price
        good_item['product_detail_price_text'] = item.product_detail_price_text
        good_item['buyer_number_text'] = item.buyer_number_text
        good_item['cart_action'] = item.cart_action
        good_item['cart_action_title'] = item.cart_action_title
        good_item['is_dm'] = item.is_dm
        good_item['show_sku'] = item.show_sku
        good_item['stocks_alarm'] = item.stocks_alarm
        good_item['status_tag'] = item.status_tag
        good_item['right_top_icon'] = item.right_top_icon
        good_item['tag'] = item.tag
        good_item['is_show_value_of_goods'] = item.is_show_value_of_goods
        good_item['is_check_delivery_address'] = item.is_check_delivery_address
        good_item['is_show_delivery_address'] = item.is_show_delivery_address
        good_item['limit_buy_detail_sku_num'] = item.limit_buy_detail_sku_num
        good_item['is_show_score'] = item.is_show_score
        good_item['is_show_koubei'] = item.is_show_koubei
        good_item['is_show_comment'] = item.is_show_comment
        good_item['is_show_new_comment_pop'] = item.is_show_new_comment_pop
        good_item['is_show_new_comment_jumei'] = item.is_show_new_comment_jumei
        good_item['img'] = item.img
        good_item['promotion_set'] = item.promotion_set
        good_item['detail_page_show_promocard'] = item.detail_page_show_promocard
        good_item['fen_qi'] = item.fen_qi
        good_item['icon_tag'] = item.icon_tag
        good_item['freight'] = item.freight
        good_item['show_single_skuview'] = item.show_single_skuview
        good_item['extra_data'] = item.extra_data
        good_item['shop_info'] = item.shop_info
        good_item['activity_list'] = item.activity_list
        good_item['price_des'] = item.price_des
        good_item['product_desc'] = item.product_desc
        good_item['relate_deal'] = item.relate_deal
        good_item['trust_info'] = item.trust_info
        good_item['is_phone_cost'] = item.is_phone_cost
        good_item['detail_comment_num'] = item.detail_comment_num
        good_item['bottom_button'] = item.bottom_button
        good_item['is_first_click_window'] = item.is_first_click_window
        good_item['countdown_time'] = item.countdown_time
        good_item['recommend_soldout_title'] = item.recommend_soldout_title
        good_item['recommend_soldout_status'] = item.recommend_soldout_status
        good_item['sellparams'] = item.sellparams
        good_item['jumei_counter_title'] = item.jumei_counter_title
        good_item['marquee'] = item.marquee
        good_item['quiz_module_detail'] = item.quiz_module_detail
        good_item['comment_list'] = item.comment_list
        good_item['graphic_details_other'] = item.graphic_details_other
        good_item['url_schema'] = item.url_schema
        good_item['yanzhidai'] = item.yanzhidai
        good_item['show_kou_bei_cate'] = item.show_kou_bei_cate
        good_item['show_cart_big_img_ab'] = item.show_cart_big_img_ab
        good_item['show_cart_big_img_onoff'] = item.show_cart_big_img_onoff
        good_item['show_comment_tab_dot'] = item.show_comment_tab_dot
        good_item['customer_service'] = item.customer_service
        good_item['sku_no_stock_click'] = item.sku_no_stock_click
        good_item['is_service_info'] = item.is_service_info
        good_item['is_show_counter'] = item.is_show_counter
        good_item['new_video_info'] = item.new_video_info
        good_item['is_has_new_short_video'] = item.is_has_new_short_video
        good_item['is_jump_app'] = item.is_jump_app
        good_item['coutuan_enter_info'] = item.coutuan_enter_info
        good_item['has_video_img'] = item.has_video_img
        good_item['video_info_test'] = item.video_info_test
        good_item['is_limited'] = item.is_limited
        good_item['hide_touch_header'] = item.hide_touch_header
        good_item['cart_host_h5'] = item.cart_host_h5
        good_item['address_list_version'] = item.address_list_version
        good_item['is_login'] = item.is_login
        good_item['address_list'] = item.address_list
        good_item['default_address'] = item.default_address
        good_item['special_deal_id'] = item.special_deal_id
        good_item['seckill_car_domain'] = item.seckill_car_domain
        good_item['seckill_car_event_status'] = item.seckill_car_event_status
        good_item['is_dj_item'] = item.is_dj_item
        good_item['comment_verify_code'] = item.comment_verify_code

        if good_item['item_id']:
            return good_item


class GoodDynamicDetailExtractor(JsonExtractor):
    item_id = JsonField(json_selector='$.data.result.item_id')
    type = JsonField(json_selector='$.data.result.type')
    status = JsonField(json_selector='$.data.result.status')
    is_sellable = JsonField(json_selector='$.data.result.is_sellable')
    selling_forms = JsonField(json_selector='$.data.result.selling_forms')
    discount = JsonField(json_selector='$.data.result.discount')
    market_price = JsonField(json_selector='$.data.result.market_price')
    size = JsonField(json_selector='$.data.result.size')
    default_sku = JsonField(json_selector='$.data.result.default_sku')
    tag_ids = JsonField(json_selector='$.data.result.tag_ids')
    show_category = JsonField(json_selector='$.data.result.show_category')
    warehouse_code = JsonField(json_selector='$.data.result.warehouse_code')
    sale_type = JsonField(json_selector='$.data.result.sale_type')
    sale_type_id = JsonField(json_selector='$.data.result.sale_type_id')
    merchant_id = JsonField(json_selector='$.data.result.merchant_id')
    product_id = JsonField(json_selector='$.data.result.product_id')
    brand_id = JsonField(json_selector='$.data.result.brand_id')
    category_v3_3 = JsonField(json_selector='$.data.result.category_v3_3')
    category_v3_4 = JsonField(json_selector='$.data.result.category_v3_4')
    category = JsonField(json_selector='$.data.result.category')
    shipping_system_id = JsonField(json_selector='$.data.result.shipping_system_id')
    product_attr_aca = JsonField(json_selector='$.data.result.product_attr_aca')
    refund_policy = JsonField(json_selector='$.data.result.refund_policy')
    exchange_policy = JsonField(json_selector='$.data.result.exchange_policy')
    value_of_goods = JsonField(json_selector='$.data.result.value_of_goods')
    tax = JsonField(json_selector='$.data.result.tax')
    anchor_uid = JsonField(json_selector='$.data.result.anchor_uid')
    is_support_refund_window = JsonField(json_selector='$.data.result.is_support_refund_window')
    countries = JsonField(json_selector='$.data.result.countries')
    author_id = JsonField(json_selector='$.data.result.author_id')
    video_id = JsonField(json_selector='$.data.result.video_id')
    is_hide_juhe_sku = JsonField(json_selector='$.data.result.is_hide_juhe_sku')
    size_attr = JsonField(json_selector='$.data.result.size_attr')
    fare = JsonField(json_selector='$.data.result.fare')
    baoyou = JsonField(json_selector='$.data.result.baoyou')
    area_code = JsonField(json_selector='$.data.result.area_code')
    area_name = JsonField(json_selector='$.data.result.area_name')
    shipping_system_type = JsonField(json_selector='$.data.result.shipping_system_type')
    shipping_time = JsonField(json_selector='$.data.result.shipping_time')
    baoyou_desc = JsonField(json_selector='$.data.result.baoyou_desc')
    baoyou_text = JsonField(json_selector='$.data.result.baoyou_text')
    wuliu_text = JsonField(json_selector='$.data.result.wuliu_text')
    guonei_baoyou = JsonField(json_selector='$.data.result.guonei_baoyou')
    bonded_area_id = JsonField(json_selector='$.data.result.bonded_area_id')
    jumei_price = JsonField(json_selector='$.data.result.jumei_price')
    start_time = JsonField(json_selector='$.data.result.start_time')
    end_time = JsonField(json_selector='$.data.result.end_time')
    second_kill_time = JsonField(json_selector='$.data.result.second_kill_time')
    buyer_number = JsonField(json_selector='$.data.result.buyer_number')
    wish_number = JsonField(json_selector='$.data.result.wish_number')
    status_num = JsonField(json_selector='$.data.result.status_num')
    sale_short_name = JsonField(json_selector='$.data.result.sale_short_name')
    sku_min_price = JsonField(json_selector='$.data.result.sku_min_price')
    sku_max_price = JsonField(json_selector='$.data.result.sku_max_price')
    product_detail_price_text = JsonField(json_selector='$.data.result.product_detail_price_text')
    buyer_number_text = JsonField(json_selector='$.data.result.buyer_number_text')
    cart_action = JsonField(json_selector='$.data.result.cart_action')
    cart_action_title = JsonField(json_selector='$.data.result.cart_action_title')
    is_dm = JsonField(json_selector='$.data.result.is_dm')
    show_sku = JsonField(json_selector='$.data.result.show_sku')
    stocks_alarm = JsonField(json_selector='$.data.result.stocks_alarm')
    status_tag = JsonField(json_selector='$.data.result.status_tag')
    right_top_icon = JsonField(json_selector='$.data.result.right_top_icon')
    tag = JsonField(json_selector='$.data.result.tag')
    is_show_value_of_goods = JsonField(json_selector='$.data.result.is_show_value_of_goods')
    is_check_delivery_address = JsonField(json_selector='$.data.result.is_check_delivery_address')
    is_show_delivery_address = JsonField(json_selector='$.data.result.is_show_delivery_address')
    limit_buy_detail_sku_num = JsonField(json_selector='$.data.result.limit_buy_detail_sku_num')
    is_show_score = JsonField(json_selector='$.data.result.is_show_score')
    is_show_koubei = JsonField(json_selector='$.data.result.is_show_koubei')
    is_show_comment = JsonField(json_selector='$.data.result.is_show_comment')
    is_show_new_comment_pop = JsonField(json_selector='$.data.result.is_show_new_comment_pop')
    is_show_new_comment_jumei = JsonField(json_selector='$.data.result.is_show_new_comment_jumei')
    img = JsonField(json_selector='$.data.result.img')
    promotion_set = JsonField(json_selector='$.data.result.promotion_set')
    detail_page_show_promocard = JsonField(json_selector='$.data.result.detail_page_show_promocard')
    fen_qi = JsonField(json_selector='$.data.result.fen_qi')
    icon_tag = JsonField(json_selector='$.data.result.icon_tag')
    freight = JsonField(json_selector='$.data.result.freight')
    show_single_skuview = JsonField(json_selector='$.data.result.show_single_skuview')
    extra_data = JsonField(json_selector='$.data.result.extra_data')
    shop_info = JsonField(json_selector='$.data.result.shop_info')
    activity_list = JsonField(json_selector='$.data.result.activity_list')
    price_des = JsonField(json_selector='$.data.result.price_des')
    product_desc = JsonField(json_selector='$.data.result.product_desc')
    relate_deal = JsonField(json_selector='$.data.result.relate_deal')
    trust_info = JsonField(json_selector='$.data.result.trust_info')
    is_phone_cost = JsonField(json_selector='$.data.result.is_phone_cost')
    detail_comment_num = JsonField(json_selector='$.data.result.detail_comment_num')
    bottom_button = JsonField(json_selector='$.data.result.bottom_button')
    is_first_click_window = JsonField(json_selector='$.data.result.is_first_click_window')
    countdown_time = JsonField(json_selector='$.data.result.countdown_time')
    recommend_soldout_title = JsonField(json_selector='$.data.result.recommend_soldout_title')
    recommend_soldout_status = JsonField(json_selector='$.data.result.recommend_soldout_status')
    sellparams = JsonField(json_selector='$.data.result.sellparams')
    jumei_counter_title = JsonField(json_selector='$.data.result.jumei_counter_title')
    marquee = JsonField(json_selector='$.data.result.marquee')
    quiz_module_detail = JsonField(json_selector='$.data.result.quiz_module_detail')
    comment_list = JsonField(json_selector='$.data.result.comment_list')
    graphic_details_other = JsonField(json_selector='$.data.result.graphic_details_other')
    url_schema = JsonField(json_selector='$.data.result.url_schema')
    yanzhidai = JsonField(json_selector='$.data.result.yanzhidai')
    show_kou_bei_cate = JsonField(json_selector='$.data.result.show_kou_bei_cate')
    show_cart_big_img_ab = JsonField(json_selector='$.data.result.show_cart_big_img_ab')
    show_cart_big_img_onoff = JsonField(json_selector='$.data.result.show_cart_big_img_onoff')
    show_comment_tab_dot = JsonField(json_selector='$.data.result.show_comment_tab_dot')
    customer_service = JsonField(json_selector='$.data.result.customer_service')
    sku_no_stock_click = JsonField(json_selector='$.data.result.sku_no_stock_click')
    is_service_info = JsonField(json_selector='$.data.result.is_service_info')
    is_show_counter = JsonField(json_selector='$.data.result.is_show_counter')
    new_video_info = JsonField(json_selector='$.data.result.new_video_info')
    is_has_new_short_video = JsonField(json_selector='$.data.result.is_has_new_short_video')
    is_jump_app = JsonField(json_selector='$.data.result.is_jump_app')
    coutuan_enter_info = JsonField(json_selector='$.data.result.coutuan_enter_info')
    has_video_img = JsonField(json_selector='$.data.result.has_video_img')
    video_info_test = JsonField(json_selector='$.data.result.video_info_test')
    is_limited = JsonField(json_selector='$.data.result.is_limited')
    hide_touch_header = JsonField(json_selector='$.data.result.hide_touch_header')
    cart_host_h5 = JsonField(json_selector='$.data.result.cart_host_h5')
    address_list_version = JsonField(json_selector='$.data.result.address_list_version')
    is_login = JsonField(json_selector='$.data.result.is_login')
    address_list = JsonField(json_selector='$.data.result.address_list')
    default_address = JsonField(json_selector='$.data.result.default_address')
    special_deal_id = JsonField(json_selector='$.data.result.special_deal_id')
    seckill_car_domain = JsonField(json_selector='$.data.result.seckill_car_domain')
    seckill_car_event_status = JsonField(json_selector='$.data.result.seckill_car_event_status')
    is_dj_item = JsonField(json_selector='$.data.result.is_dj_item')
    comment_verify_code = JsonField(json_selector='$.data.result.comment_verify_code')
